Jfsg team page
subvisual/westtowest pull request #5
Opened 2016-08-29 21:51 UTC by jfsgomes

Created a new page called "Team"  and moved the "officers" and "boards" from the index to there.
I also refactored the grid component, to unclutter the html file, by using selectors.

2016-08-30 00:42 UTC, joaojusto commented on app/styles/components/_hero.scss
> +$team-margin-small: 10px;
The naming doesn´t seem right to me. Usually in `SUIT CSS`, the variables names start with the `component` name. You can read more about the naming convention and component scope [here](https://github.com/suitcss/suit/blob/master/doc/components.md#component-scope)

2016-08-30 00:42 UTC, joaojusto commented on app/styles/components/_hero.scss
> +.Hero-title--team {
I think that in `SUIT CSS` we don't apply `modifiers` to `descendants`. In this case, we already have a modifier for the `Hero` components called `--team` so why not nest this rule inside it?  It also seems to me that you are creating   a new `descendant` unnecessarily. Why don't you do something like this:

```
.Hero.Hero--Team {
  background-image: url('../images/officers-board@2x.png');

  .Hero-title {
    margin-top: $team-margin-small;
  }
}
```

2016-08-30 00:42 UTC, joaojusto commented on app/styles/components/_logo.scss
> +.LogoLighthouse {
I think that this is can probably be a new `component`. What do you think?

2016-08-30 00:43 UTC, joaojusto commented on app/styles/components/_panel.scss
> +.Panel--solidLightBlue {
I know that we already have a couple of modifiers named like this in here, but I think that this is wrong. The name should be tied to the `function` of the component, not to the `style`. If we give names based on style, as soon as it changes (let's say that this modifier should now put the background in a shade of `red`) the name stops to make sense.

2016-08-30 00:43 UTC, joaojusto commented on app/styles/components/_person.scss
> +$person-top-margin: 13px;
This margin seems a bit random to me, can this be a design error?

2016-08-30 09:30 UTC, jfsgomes commented on app/styles/components/_person.scss
> +$person-top-margin: 13px;
I checked with @fcbaila and he confirmed it to be 13px.

2016-08-30 09:42 UTC, jfsgomes commented on app/styles/components/_hero.scss
> +.Hero-title--team {
:+1:

2016-08-30 09:44 UTC, jfsgomes commented on app/styles/components/_hero.scss
> +$team-margin-small: 10px;
:+1: changed it to "hero-margin-small"

2016-08-30 10:03 UTC, jfsgomes commented on app/styles/components/_logo.scss
> +.LogoLighthouse {
It makes sense, a bit in the same way we already got Grid and SponsorGrid.

2016-08-30 16:26 UTC, joaojusto commented on app/styles/components/_hero.scss
> +  margin-top: $hero-margin-small;
Indentation is wrong

2016-08-30 16:26 UTC, joaojusto commented on app/styles/components/_hero.scss
> +  text-align: center;
same

2016-08-30 16:27 UTC, joaojusto commented on app/styles/components/_logo-lighthouse.scss
> +}
Missing new line at end of file

2016-08-30 16:28 UTC, joaojusto commented
After those code style fixes if @frmendes doesn't have anything else to say :shipit:

2016-08-31 10:18 UTC, frmendes commented on app/styles/components/_hero.scss
> +  margin-top: $hero-margin-small;
Update on this?

2016-08-31 10:18 UTC, frmendes commented on app/styles/components/_hero.scss
> +  text-align: center;
Update on this?

2016-08-31 10:18 UTC, frmendes commented on app/styles/components/_logo-lighthouse.scss
> +}
Update on this?

2016-08-31 10:19 UTC, frmendes commented on app/styles/components/_grid.scss
> +}
I'm not sure how I feel about making these three assumptions or just using a `Grid--withMargin` modifier. What do you think? @joaojusto

2016-08-31 10:43 UTC, joaojusto commented on app/styles/components/_grid.scss
> +}
I don't see these as assumptions. These are the component rules, this component is supposed to behave like this in every situation. If in the future we find a scenario in which the `Grid` should behave differently then we can create a `modifier` or if the rules are way different a whole new `component`

2016-09-01 10:20 UTC, jfsgomes commented on app/styles/components/_grid.scss
> +}
I confirmed with @fcbaila that this Grid is not supposed to have more than two columns, with any new members to be added into a new row. 
I think this validates these assumptions, which allows to remove some repetition on the html, specially if more board members of officers are added in the future.

2016-09-01 10:22 UTC, jfsgomes commented on app/styles/components/_hero.scss
> +  margin-top: $hero-margin-small;
fixed

2016-09-01 10:22 UTC, jfsgomes commented on app/styles/components/_hero.scss
> +  text-align: center;
fixed

2016-09-01 10:22 UTC, jfsgomes commented on app/styles/components/_logo-lighthouse.scss
> +}
fixed

2016-09-21 19:30 UTC, frmendes commented on app/styles/components/_panel.scss
> +.Panel--solidLightBlue {
Any updates on this? I don't know if we should enforce it because it's already been used on the rest of the project, but your call @joaojusto

2016-09-21 19:31 UTC, frm reviewed
I have nothing to add except that one comment on the diff

2016-10-03 17:42 UTC, frm requested changes

2016-10-03 17:42 UTC, frmendes commented on app/index.html
> +
Unnecessary line

2016-10-03 17:42 UTC, frmendes commented on app/styles/components/_person.scss
>    .Person-information {
Missing newline

2016-10-03 17:45 UTC, frm approved these changes

2016-10-03 17:54 UTC, merged