Testimonials slider
subvisual/westtowest pull request #7
Opened 2016-09-14 17:43 UTC by sight92

Resize function created to solve issue with the entire panel being resized automatically as you scroll through the slides;

2016-09-21 19:32 UTC, frmendes commented on app/index.html
> +    <script src="/bower_components/slider-pro/dist/js/jquery.sliderPro.js"></script>
Is there a minified version of this?

2016-09-21 19:33 UTC, frmendes commented on app/styles/components/_panel.scss
> +
Unnecessary newline.

2016-09-21 19:33 UTC, frmendes commented on app/scripts/init-carousel.js
> +});
No newline at end of file.

2016-09-21 19:34 UTC, frmendes commented on app/styles/components/_panel.scss
> +  .Panel-titleImage {
I don't think these should be nested. Since you are using a modifier, it's not expected to have any changes on other elements.

2016-09-21 19:34 UTC, frmendes commented on app/styles/components/_testimonials.scss
> +
Unnecesary newline

2016-09-21 19:35 UTC, frmendes commented on app/styles/components/_testimonials.scss
> +//    background-size: contain;
If it's not being used, can we remove this comment?

2016-09-21 19:35 UTC, frmendes commented on app/styles/components/_testimonials.scss
> +//    background-size: contain;
If it's not being used, can we remove this comment?

2016-09-21 19:35 UTC, frmendes commented on app/styles/theme.scss
> +$Theme-margin-smaller: 13px;
We usually use `xSmall` if it's less than `small`. Your call here, though.

2016-09-21 19:36 UTC, frmendes commented on app/index.html
> +
Unnecessary newline

2016-09-21 19:37 UTC, frmendes commented on bower.json
> +    "promise": "^7.1.1"
Is this a dependency of `slider-pro`?

2016-09-21 19:37 UTC, frm requested changes

2016-09-22 00:27 UTC, sight92 commented on app/styles/components/_panel.scss
> +  .Panel-titleImage {
I understand what you're saying, I merely replicated code that was already in place for Panel--blue, the need for this arose from having changed the bgColor of the panel; text and titleImg color would then change from thematic dark to a light color.
I should create a modifier class for Panel-titleImage something like Panel-titleImage--light/white for specials cases where titleImage needs to be white, and then manually apply that class in the markup.
Then refactor both of these usages on lines 73(Panel--blue) and line 93(Panel--lightBlue), right?

2016-09-22 00:37 UTC, sight92 commented on bower.json
> +    "promise": "^7.1.1"
yes, although it's not explicitly stated anywhere related to the project, it arose from installing the plugin through bower.

2016-09-22 00:43 UTC, sight92 commented on app/index.html
> +    <script src="/bower_components/slider-pro/dist/js/jquery.sliderPro.js"></script>
minified version was installed through bower and is present inside plugin folder at bower_components. However, seeing as how these lines were auto generated by bower I'm not sure manually editing this to use the min version would be the best option.
Is there some production flag I can use with bower?
Same problem is occurring with jquery.

2016-09-22 00:43 UTC, sight92 commented on app/styles/components/_panel.scss
> +
:+1:

2016-09-22 00:43 UTC, sight92 commented on app/scripts/init-carousel.js
> +});
:+1:

2016-09-22 00:44 UTC, sight92 commented on app/styles/components/_testimonials.scss
> +
:+1:

2016-09-22 00:44 UTC, sight92 commented on app/styles/components/_testimonials.scss
> +//    background-size: contain;
:+1:

2016-09-22 00:44 UTC, sight92 commented on app/styles/components/_testimonials.scss
> +//    background-size: contain;
:+1:

2016-09-22 00:45 UTC, sight92 commented on app/styles/theme.scss
> +$Theme-margin-smaller: 13px;
changed to `xSmall` for convention purposes
:+1:

2016-09-22 00:45 UTC, sight92 commented on app/index.html
> +
:+1:

2016-09-28 17:21 UTC, frm approved these changes

2016-09-28 17:21 UTC, frmendes commented
As discussed in person, this can be merged.

2016-09-28 18:23 UTC, merged